const express = require('express')
const router = express.Router()
const exhibition = require('../controllers/exhibition')
const verifyToken = require('../middlewares/index')
router.post('/exhibition', verifyToken, exhibition.createExhibition)
router.get('/exhibition', exhibition.getExhitions)
router.delete('/exhibition/:id', verifyToken, exhibition.deleteExhibition)
router.get('/exhibition/:id', exhibition.findExhById)
router.put('/exhibition/:id', verifyToken, exhibition.updateExh)
router.put('/sortexhibition', verifyToken, exhibition.sortWork)
module.exports = router
