const express = require('express')
const router = express.Router()
const newInfo = require('../controllers/new')
const verifyToken = require('../middlewares/index')
router.post('/new', verifyToken, newInfo.createNew)
router.get('/new', newInfo.getNews)
router.get('/new/:id', newInfo.findNewById)
router.delete('/new/:id', verifyToken, newInfo.deleteNew)
router.put('/new/:id', verifyToken, newInfo.updateNew)
router.put('/sortnew', verifyToken, newInfo.sortNewsOrder)
module.exports = router
